/* This file was generated by ConfigHeader using the Zig Build System. */
#define PACKAGE_NAME "VileBoom"
#define PACKAGE_TARNAME "vileboom"
#define WAD_DATA "vileboom.wad"
#define PACKAGE_VERSION "0.0.0"
#define PACKAGE_STRING "vileboom 0.0.0"

#define DOOMWADDIR "/usr/local/share/games/doom"
#define VTEC_ABSOLUTE_PWAD_PATH "/usr/local/share/games/doom"

/* #undef WORDS_BIGENDIAN */

#define HAVE_GETOPT 
#define HAVE_MMAP 
/* #undef HAVE_CREATE_FILE_MAPPING */
#define HAVE_STRSIGNAL 
#define HAVE_MKSTEMP 
#define HAVE_GETPWUID 

#define HAVE_SYS_WAIT_H 
#define HAVE_UNISTD_H 
#define HAVE_ASM_BYTEORDER_H 
#define HAVE_DIRENT_H 

#define HAVE_LIBSDL2_IMAGE 
#define HAVE_LIBSDL2_MIXER 

#define HAVE_LIBMAD 
#define HAVE_LIBFLUIDSYNTH 
#define HAVE_LIBDUMB 
#define HAVE_LIBVORBISFILE 
#define HAVE_LIBPORTMIDI 

#define SIMPLECHECKS 

/* #undef RANGECHECK */

